theme: jekyll-theme-leap-day
title: Smith ABE 516X Project
description: My ABE 516X project. The goal of this project is to address an issue within animal production ventilation systems that use airfilters.
