theme: jekyll-theme-leap-day
title: EAFTC Pilot Scale Model Development
description: Environmental Air Filter Testing Chamber model development. The goal of this project is to address an issue within animal production ventilation systems that use air filters.
